Comment out root eslintrc extends
It was causing a conflict with next.js generated eslintrc
inside apps/contatempo

Error: Plugin "react-hooks" was conflicted between ".eslintrc.json" [...]